// Create tables
POST http://localhost:3000/api/users/tables

###

// Create user:
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "email": "test1@email.com",
    "password": "XX1password"
}

###

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "email": "test2@email.com",
    "password": "XX2password"
}

###

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "email": "test3@email.com",
    "password": "XX3password"
}

###
// Get all users
GET http://localhost:3000/api/users HTTP/1.1
content-type: application/json

###
// Get one user
GET http://localhost:3000/api/users/2 HTTP/1.1
content-type: application/json

###
// Update one user's information
PUT http://localhost:3000/api/users/2 HTTP/1.1
content-type: application/json

{
    "email": "changed2@email.com",
    "password": "NEW2__XXpassword"
}

###
// Delete all users
DELETE http://localhost:3000/api/users HTTP/1.1

### 
// Delete one user
DELETE http://localhost:3000/api/users/2 HTTP/1.1

###
// Delete users table
DELETE http://localhost:3000/api/users/tables HTTP/1.1

###
// Create tables
POST http://localhost:3000/api/transactions/tables

###
// Get all users
GET http://localhost:3000/api/transactions HTTP/1.1
content-type: application/json

### 
// Delete one user
DELETE http://localhost:3000/api/transactions/1 HTTP/1.1